# config-private.yaml
apprise:
  urls:
    - "discord://{WebhookID}/{WebhookToken}" # Replace with your actual Apprise service URLs
default_geolocation: US # Replace with your country code https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
