# config.yaml
apprise:
  summary: ON_ERROR
  notify:
    uncaught-exceptions: True # True or False
    incomplete-promotions: True # True or False
retries:
  base_delay_in_seconds: 14.0625 # base_delay_in_seconds * 2^max = 14.0625 * 2^6 = 900 = 15 minutes
  max: 8
  strategy: EXPONENTIAL
logging: DEBUG # DEBUG or INFO
