# config.yaml
apprise:
  summary: always
  urls:
    - 'discord://WebhookID/WebhookToken'  # Replace with your actual Apprise service URLs
attempts:
  base_delay_in_seconds: 60
  max: 6
  strategy: constant
