services:
  ms-rewards:
    container_name: ms-rewards-farmer
    build: .
    image: ms-rewards-farmer:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - RUN_ONCE=false
      - CRON_SCHEDULE=0 4 * * *
